#!/bin/bash
#
while [ 1 ]
do
CHOICE=$(
whiptail --backtitle " Программа написана на whiptail"\
         --title "Редактирование и настройка Xterm"\
         --menu "\n
 XTerm не является эмулятором терминала. Это окно оболочки.\n
 Клавишами верх/низ выберите справку и нажмите enter.
 Для выхода выберите Exit." 0 0 20\
  "1)" "Следите за синтаксисoм и условиями Xterm!"\
  "2)" "Установка Xterm"\
  "3)" "Комментарий"\
  "4)" "Горячие клавиши"\
  "5)" "Показать скрипт горячих клавиш"\
  "6)" "Настройка xterm"\
  "7)" "Размер и вид шрифта"\
  "8)" "Цвет заднего фона xterm"\
  "9)" "Цвет текста xterm"\
 "10)" "Kурсор"\
 "11)" "Полоса прокрутки"\
 "12)" "Цветной XTerm"\
 "13)" "Меню"\
 "14)" "Просмотр миниатюр lsix"\
 "15)" "15"\
 "16)" "16"\
 "17)" "17"\
 "18)" "18"\
 "19)" "19"\
 "20)" "20"\
 "21)" "21"\
 "22)" "22"\
 "23)" "23"\
 "24)" "24"\
 "25)" "25"\
 "26)" "26"\
 "27)" "27"\
 "28)" "Показать .Xresources"\
 "29)" "Сайты"\
 "30)" "Exit"\
 3>&2 2>&1 1>&3
)

result=$()
case $CHOICE in
       "1)")   
result="Следите за синтаксисoм и условиями Xterm!"
        ;;
       "2)")   
result=" sudo apt-get install -y xterm "
        ;;
       "3)")
result=" !
 любой текс после данного знака читается как комментарий
 \n
"
        ;;
       "4)")   
result="\n
 Нажмите клавиши: \n
 Открыть xterm: alt enter
 Копировать:    alt shift c
 Вставить:      alt shift v \n
 "
        ;;
       "5)")
whiptail --textbox "/home/grannik/TeConfiguration/ConfXterm/hotkeys.txt" 10 0 --scrolltext
        ;;
       "6)")
result="\n
 Настройка xterm происходит путём правки файла ~/.Xresources \n
 Первое. Создать файл ~/.Xresources:
 touch ~/.Xresources \n
 Второе. Отредактировать файл ~/.Xresources
 ne это любой редактор в терминале:
 ne ~/.Xresources \n
 Чтобы изменения в файле вступили в силу, необходимо перечитать его командой:
 xrdb ~/.Xresources
 или загрузить заново:
 xrdb -load ~/.Xresources \n
 Посмотреть какие настройки используются:
 xrdb -query -all \n
 "
        ;;
       "7)")
result="xterm*faceName: Andale:style=Mono:size=10"
        ;;
       "8)")   
result=" \n
 Цвет фона может быть также задан кодом #000000 или rgb:00/00/00
 xterm*background: black"
        ;;
       "9)")  
result="xterm*foreground: white"
        ;;
       "10)")
result=" \n
 Цвет курсора:
 xterm*cursorColor:green \n
 Мигание курсора:
 xterm*cursorBlink:true \n
 "
        ;;
       "11)")   
result="\n
 Полоса прокрутки есть:
 xterm*scrollBar:true \n
 Плолсы прокрутки нет:
 xterm*scrollBar:false\n
 Полоса прокрутки справа есть:
 xterm*rightScrollBar:true\n
 Полосы прокрутки справа нет:
 xterm*rightScrollBar:false\n
 "
        ;;
       "12)")
result=" Все настройки находятся в файлах: 
 .bash_profile
 .bashrc \n
"
        ;;
       "13)")
result=" \n
 По умолчанию у xterm отсутствует строка меню.
 Для получения доступа к одному трёх  меню xterm необходимо, удерживая клавишу Control,
 нажать левую, среднюю или правую клавишу мыши. \n
 Настройка меню:
 XTerm.vt100.geometry: 80x32 "
        ;;
       "14)")   
whiptail --textbox "/home/grannik/TeConfiguration/ConfXterm/lsix.txt" 0 0 --scrolltext
        ;;
       "15)")
result="15"
        ;;
       "16)")
result="16"
        ;;
       "17)")
result="17"
        ;;
       "18)")
result="18"
        ;;
       "19)")   
result="19"
        ;;
       "20)")
result="20"
        ;;
       "21)")   
result="21"
        ;;
       "22)")   
result="22"
        ;;
       "23)")   
result="23"
        ;;
       "24)")   
result="24"
        ;;
       "25)")   
result="25"
        ;;
       "26)")
result="26"
        ;;
       "27)")   
result="27"
        ;;
       "28)")   
whiptail --textbox "/home/grannik/TeConfiguration/ConfXterm/xresources" 0 0 --scrolltext
        ;;
        "29)")
result=" lsix
 Просмотр миниатюр изображений в терминале
 http://rus-linux.net/MyLDP/consol/Thumbnail_Images_In_Terminal.html \n
 "
        ;;
        "30)")   
exit
        ;;
esac
whiptail --msgbox "$result" 0 0
done
exit